[package]
name = "docsearch-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
colored = "2.0.0"
serde = "1.0.159"
serde_json = "1.0.95"
tungstenite = "0.18.0"
